os: linux
dist: bionic
language: c
addons:
  apt:
    packages:
    - libxml2-utils
services:
- docker
jobs:
  include:
  - stage: run-mayhem
    script:
    - docker build -t ${IMAGE_TAG} -f Dockerfile .
    - mayhem/scripts/run-mayhem.sh
env:
  global:
    # Additional environment values - either specify here or in your
    # Travis-CI job configuration.
    # - MAYHEM_URL=https://my-company.forallsecure.com
    # - DOCKER_REGISTRY=my-company.forallsecure.com:5000
    # - IMAGE_TAG=my-company.forallsecure.com:5000/mayhem-netflix-dial-reference:${TRAVIS_BRANCH}
    # - MAYHEM_TOKEN="AT1.abcdefg"
    - secure: "XyfOmIoOaLiyT8e1+gtHC6nbeUpY0QsHqns1uPyWn0oAuHQmeZjqtnF/ENavsPIxypKCkp6BxtMpB47Mrjz6pIAodYPmSgQP7L8IIQd6GAtNKIx+SmvXv0/BhLWz5vM7CxCukgAed3ZBaP8IC+1hlGqq5rfWai7cqcgmcJB4TSiN7+isrO7dO54QISPClstpMImd3EY/sODjsJhaY2i3h2g2YR5ymB5dpQXruvlvWl2/sn1X/oroa6+rDZuyYtZrPXW7u7dtybJgtWqMMTKsQDq75r+b4fsEyacsT5ai1xNzyV+mYATz718DXfjaV9XmdDmiLVn5K7SHWJdlDyHdCkqAMmigrhtzmxBRX4dL2uyzI+hy+8XHqe6L09q3RgDVA3nZdPtjDstwyUgSfjllbFqHQAA4N0kF6jobdj/ULnwEAP6gGxhKQE+8dRB9g0WY+FMEhF3YI40ibqzhaMDwssHYUj0bWHq3rfeC5I6B6BaF5hQ7Pw+68TLgwlOa5F0OT3CYU2uVsTLHc5I0U3q5zNQFXvZMGYLz1em/rN3dFebnWiVoaur/HykCk0hye8vDWswy5L9AkjidKLB0BJHehyqVevGJ7+nIDs1PDhWr9sjdA5ml317ocPE+ghxNtJ9MTo57nidhyxizUKEoEXV31mh45Pog9NC7ieu4Od5bsWA="
